### ISSUE TITLE
ASP.NET Core enriches wrong IP when proxy is used

### ISSUE THREAD

**Issue by klinki** [mo-esmp/serilog-enrichers-clientinfo#1]
Hello,
first of all, thank you for great enricher :) 

I have a small problem with it - it doesn't work correctly for ASP.NET Core when proxy is used.
It works fine for full ASP.NET framework. It is caused by handling those cases differently with `#if NETFULL` macro.

Is there any reason for it? Couldn't also .NET Core version read X-Forwarded-For headers?

(Also, when used on Azure, azure adds also port number, but that's whole different issue)

```csharp
#if NETFULL
        private string GetIpAddress()
        {
            var ipAddress = _contextAccessor.HttpContext.Request.ServerVariables["HTTP_X_FORWARDED_FOR"];

            if (!string.IsNullOrEmpty(ipAddress))
            {
                var addresses = ipAddress.Split(',');
                if (addresses.Length != 0)
                    return addresses[0];
            }

            return _contextAccessor.HttpContext.Request.ServerVariables["REMOTE_ADDR"];
        }

#else
     private string GetIpAddress()
     {
        return _contextAccessor.HttpContext.Connection.RemoteIpAddress.ToString();
     }
#endif
```

**Comment by mo-esmp** [comment]
Thank you for reporting the bug and pull request. I forgot to check proxy for .NET Core and the common problem of a project without the test.
