### ISSUE TITLE
Make ip header variable configurable?

### ISSUE THREAD

**Issue by zyofeng** [mo-esmp/serilog-enrichers-clientinfo#11]
Currently this lib uses X-forwarded-for to get client ip, however in some proxy environments i.e. Cloudflare.
Ips are piped through custom http headers  (CF-Connecting-IP)
https://developers.cloudflare.com/fundamentals/get-started/reference/http-request-headers/

Would it be possible to make this header variable name configurable with defaults to X-forwarded-for?

Regards

**Comment by mo-esmp** [comment]
It's possible, however, need to figure out how to set the configuration for enricher in `appsettings.json` file

**Comment by nblumhardt** [comment]
It's the same syntax as `WriteTo`; there isn't a lot of documentation, but the Serilog.Settings.Configuration sample project has a pretty complete example:

https://github.com/serilog/serilog-settings-configuration/blob/dev/sample/Sample/appsettings.json#L66

HTH,
Nick

**Comment by mo-esmp** [comment]
@zyofeng Sorry for the delay, please update to version `1.2.0`.

**Comment by zyofeng** [comment]
No worries, thank you!
