### ISSUE TITLE
ASP.NET Core 2.1 Support?

### ISSUE THREAD

**Issue by spottedmahn** [mo-esmp/serilog-enrichers-clientinfo#3]
On startup of our 2.1 app we're getting:

>FileLoadException: Could not load file or assembly 'Microsoft.AspNetCore.Http, Version=2.2.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. 

```c#
loggerConfiguration..Enrich.WithClientIp()
```

**PS**, thanks for creating this enricher! 🤝

**Comment by spottedmahn** [comment]
Interesting, this looks right:

![image](https://user-images.githubusercontent.com/14079228/101271708-4edf4380-3753-11eb-9297-7f3338d94f32.png)

**Comment by spottedmahn** [comment]
![image](https://user-images.githubusercontent.com/14079228/101271845-9e723f00-3754-11eb-8b39-3dd28bcb025a.png)

**Comment by mo-esmp** [comment]
I've merged your pull request, please upgrade the package to version 1.1.1.

**Comment by spottedmahn** [comment]
thanks for the quick turn-around! 🤝

gtg 🎉
