### ISSUE TITLE
Wrong Serilog version in csproj?

### ISSUE THREAD

**Issue by spottedmahn** [mo-esmp/serilog-enrichers-clientinfo#5]
According to the [nuspec](https://github.com/mo-esmp/serilog-enrichers-clientinfo/blob/master/Serilog.Enrichers.ClientInfo.nuspec), the Serilog dependency is 2.7.1:

```xml
<group targetFramework="netstandard2.0">
	<dependency id="Microsoft.AspNetCore.Http" version="2.1.1" />
	<dependency id="Serilog" version="2.7.1" />
</group>
```

but the [csproj ](https://github.com/mo-esmp/serilog-enrichers-clientinfo/blob/master/src/Serilog.Enrichers.ClientInfo/Serilog.Enrichers.ClientInfo.csproj)is referencing 2.9.0:

```xml
<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0'">
	<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.1.1" />
	<PackageReference Include="Serilog" Version="2.9.0" />
</ItemGroup>
```

**Comment by mo-esmp** [comment]
@spottedmahn thank you again. please upgrade to version 1.1.2.

**Comment by spottedmahn** [comment]
nice, thanks!

**Comment by spottedmahn** [comment]
fix via https://github.com/mo-esmp/serilog-enrichers-clientinfo/commit/ad3f73504b8a589dfd5a31dba094babbfe5e49ae
